import type { Project } from './types'

export const PROJECTS_SEED: Project[] = [
  {
    id: 'proj-1',
    code: 'PRJ-0001',
    name: 'Riverside Towers',
    clientId: 'client-1',
    clientName: 'Greenfield Developers',
    type: 'Residential',
    status: 'in_progress',
    location: 'Whitefield, Bengaluru',
    projectManager: 'Priya Nair',
    startDate: '2026-01-15',
    endDate: '2026-12-20',
    budget: 85000000,
    spent: 47500000,
    progress: 56,
    description: 'A 3-tower residential complex with 240 apartments, clubhouse, and landscaped gardens.',
    milestones: [
      { id: 'm1', label: 'Foundation & Excavation', dueDate: '2026-02-28', done: true },
      { id: 'm2', label: 'Tower A Structure', dueDate: '2026-06-30', done: true },
      { id: 'm3', label: 'Tower B & C Structure', dueDate: '2026-09-30', done: false },
      { id: 'm4', label: 'MEP & Finishing', dueDate: '2026-11-30', done: false },
    ],
    tasks: [
      { id: 't1', title: 'Electrical rough-in — Block C', assignee: 'Suresh Kumar', status: 'in_progress', dueDate: '2026-07-10' },
      { id: 't2', title: 'Plumbing inspection — Tower B', assignee: 'Manoj Rao', status: 'todo', dueDate: '2026-07-14' },
      { id: 't3', title: 'Structural audit — Tower A', assignee: 'Suresh Kumar', status: 'done', dueDate: '2026-06-28' },
    ],
    expenses: [
      { id: 'e1', category: 'Steel & Rebar', amount: 4200000, date: '2026-06-18' },
      { id: 'e2', category: 'Labour Wages', amount: 1850000, date: '2026-06-25' },
      { id: 'e3', category: 'Ready-mix Concrete', amount: 3100000, date: '2026-07-01' },
    ],
    documents: [
      { id: 'd1', name: 'Structural Drawings Rev 3.pdf', type: 'Drawing', uploadedAt: '2026-05-02' },
      { id: 'd2', name: 'BBMP Building Permit.pdf', type: 'Permit', uploadedAt: '2026-01-10' },
    ],
  },
  {
    id: 'proj-2',
    code: 'PRJ-0002',
    name: 'Sunrise Residency',
    clientId: 'client-2',
    clientName: 'Vikram Singh',
    type: 'Residential',
    status: 'in_progress',
    location: 'Kondapur, Hyderabad',
    projectManager: 'Priya Nair',
    startDate: '2026-03-01',
    endDate: '2026-10-15',
    budget: 12500000,
    spent: 5400000,
    progress: 40,
    description: 'Custom 3BHK independent villa with modern facade and rooftop garden.',
    milestones: [
      { id: 'm1', label: 'Foundation', dueDate: '2026-03-25', done: true },
      { id: 'm2', label: 'Superstructure', dueDate: '2026-06-15', done: true },
      { id: 'm3', label: 'Finishing & Interiors', dueDate: '2026-09-30', done: false },
    ],
    tasks: [
      { id: 't1', title: 'Interior wall plastering', assignee: 'Manoj Rao', status: 'in_progress', dueDate: '2026-07-08' },
      { id: 't2', title: 'Facade cladding order', assignee: 'Priya Nair', status: 'todo', dueDate: '2026-07-20' },
    ],
    expenses: [
      { id: 'e1', category: 'Cement & Aggregates', amount: 980000, date: '2026-06-10' },
      { id: 'e2', category: 'Labour Wages', amount: 620000, date: '2026-06-22' },
    ],
    documents: [{ id: 'd1', name: 'Villa Architectural Plan.pdf', type: 'Drawing', uploadedAt: '2026-02-15' }],
  },
  {
    id: 'proj-3',
    code: 'PRJ-0003',
    name: 'Tech Park Block D',
    clientId: 'client-3',
    clientName: 'Skyline Infra Ltd',
    type: 'Commercial',
    status: 'planning',
    location: 'Hinjewadi, Pune',
    projectManager: 'Arun Mehta',
    startDate: '2026-08-01',
    endDate: '2027-11-30',
    budget: 320000000,
    spent: 8500000,
    progress: 4,
    description: 'A 12-floor Grade-A commercial office building with basement parking for 400 cars.',
    milestones: [{ id: 'm1', label: 'Design & Approvals', dueDate: '2026-07-31', done: false }],
    tasks: [{ id: 't1', title: 'Soil testing report review', assignee: 'Arun Mehta', status: 'in_progress', dueDate: '2026-07-12' }],
    expenses: [{ id: 'e1', category: 'Soil Testing & Survey', amount: 850000, date: '2026-06-05' }],
    documents: [{ id: 'd1', name: 'Environmental Clearance Application.pdf', type: 'Permit', uploadedAt: '2026-06-01' }],
  },
  {
    id: 'proj-4',
    code: 'PRJ-0004',
    name: 'Lakeview Apartments Phase 2',
    clientId: 'client-1',
    clientName: 'Greenfield Developers',
    type: 'Residential',
    status: 'on_hold',
    location: 'Sarjapur Road, Bengaluru',
    projectManager: 'Priya Nair',
    startDate: '2025-11-01',
    endDate: '2026-10-31',
    budget: 64000000,
    spent: 18200000,
    progress: 22,
    description: 'Second phase of the Lakeview community — 3 residential blocks with amenities.',
    milestones: [{ id: 'm1', label: 'Excavation', dueDate: '2025-12-15', done: true }],
    tasks: [{ id: 't1', title: 'Resolve boundary dispute', assignee: 'Arun Mehta', status: 'todo', dueDate: '2026-07-25' }],
    expenses: [{ id: 'e1', category: 'Legal & Compliance', amount: 320000, date: '2026-05-20' }],
    documents: [],
  },
  {
    id: 'proj-5',
    code: 'PRJ-0005',
    name: 'Highway Bridge Retrofit',
    clientId: 'client-4',
    clientName: 'State PWD Department',
    type: 'Infrastructure',
    status: 'completed',
    location: 'NH-48, Chennai',
    projectManager: 'Arun Mehta',
    startDate: '2025-04-01',
    endDate: '2026-03-31',
    budget: 45000000,
    spent: 43200000,
    progress: 100,
    description: 'Structural retrofit and widening of a 4-lane highway bridge.',
    milestones: [{ id: 'm1', label: 'Final Handover', dueDate: '2026-03-31', done: true }],
    tasks: [],
    expenses: [],
    documents: [{ id: 'd1', name: 'Completion Certificate.pdf', type: 'Certificate', uploadedAt: '2026-04-02' }],
  },
  {
    id: 'proj-6',
    code: 'PRJ-0006',
    name: 'Precision Auto Warehouse',
    clientId: 'client-5',
    clientName: 'Precision Auto Components',
    type: 'Industrial',
    status: 'in_progress',
    location: 'Oragadam, Chennai',
    projectManager: 'Priya Nair',
    startDate: '2026-02-10',
    endDate: '2026-09-30',
    budget: 28000000,
    spent: 15600000,
    progress: 62,
    description: 'A 90,000 sq.ft. pre-engineered steel warehouse with loading docks and office block.',
    milestones: [{ id: 'm1', label: 'PEB Erection', dueDate: '2026-06-30', done: true }],
    tasks: [{ id: 't1', title: 'Fire safety system install', assignee: 'Suresh Kumar', status: 'in_progress', dueDate: '2026-07-18' }],
    expenses: [{ id: 'e1', category: 'PEB Structure', amount: 9200000, date: '2026-05-15' }],
    documents: [{ id: 'd1', name: 'Fire NOC Application.pdf', type: 'Permit', uploadedAt: '2026-06-20' }],
  },
  {
    id: 'proj-7',
    code: 'PRJ-0007',
    name: 'Emerald Heights',
    clientId: 'client-2',
    clientName: 'Vikram Singh',
    type: 'Residential',
    status: 'planning',
    location: 'Wakad, Pune',
    projectManager: 'Priya Nair',
    startDate: '2026-09-01',
    endDate: '2027-08-31',
    budget: 52000000,
    spent: 1200000,
    progress: 2,
    description: 'Boutique 4-storey apartment building with 16 premium units.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-8',
    code: 'PRJ-0008',
    name: 'Coastal Logistics Park',
    clientId: 'client-5',
    clientName: 'Precision Auto Components',
    type: 'Industrial',
    status: 'in_progress',
    location: 'Ennore, Chennai',
    projectManager: 'Arun Mehta',
    startDate: '2026-04-01',
    endDate: '2027-01-31',
    budget: 68000000,
    spent: 22400000,
    progress: 33,
    description: 'Multi-unit logistics and warehousing park near Ennore port.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-9',
    code: 'PRJ-0009',
    name: 'Silver Oak Villas',
    clientId: 'client-1',
    clientName: 'Greenfield Developers',
    type: 'Residential',
    status: 'completed',
    location: 'Devanahalli, Bengaluru',
    projectManager: 'Priya Nair',
    startDate: '2025-01-10',
    endDate: '2026-01-05',
    budget: 38000000,
    spent: 37200000,
    progress: 100,
    description: 'Gated community of 24 independent villas with clubhouse.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-10',
    code: 'PRJ-0010',
    name: 'Metro Link Flyover',
    clientId: 'client-4',
    clientName: 'State PWD Department',
    type: 'Infrastructure',
    status: 'in_progress',
    location: 'Anna Salai, Chennai',
    projectManager: 'Arun Mehta',
    startDate: '2026-05-01',
    endDate: '2027-04-30',
    budget: 120000000,
    spent: 34500000,
    progress: 29,
    description: 'Elevated flyover connecting Anna Salai to the metro corridor.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-11',
    code: 'PRJ-0011',
    name: 'Greenfield Business Park',
    clientId: 'client-3',
    clientName: 'Skyline Infra Ltd',
    type: 'Commercial',
    status: 'on_hold',
    location: 'Kharadi, Pune',
    projectManager: 'Arun Mehta',
    startDate: '2025-10-01',
    endDate: '2026-12-31',
    budget: 210000000,
    spent: 58000000,
    progress: 27,
    description: 'IT park with three office towers and a food court block.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-12',
    code: 'PRJ-0012',
    name: 'Palm Meadows Extension',
    clientId: 'client-2',
    clientName: 'Vikram Singh',
    type: 'Residential',
    status: 'in_progress',
    location: 'Yelahanka, Bengaluru',
    projectManager: 'Priya Nair',
    startDate: '2026-02-15',
    endDate: '2026-11-15',
    budget: 41000000,
    spent: 19800000,
    progress: 48,
    description: 'Extension phase adding 30 row-houses to the Palm Meadows layout.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-13',
    code: 'PRJ-0013',
    name: 'Sunrise Mall Renovation',
    clientId: 'client-3',
    clientName: 'Skyline Infra Ltd',
    type: 'Commercial',
    status: 'in_progress',
    location: 'FC Road, Pune',
    projectManager: 'Arun Mehta',
    startDate: '2026-03-10',
    endDate: '2026-09-10',
    budget: 15000000,
    spent: 9200000,
    progress: 61,
    description: 'Facade and interior renovation of an existing retail mall.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-14',
    code: 'PRJ-0014',
    name: 'Riverfront Public Plaza',
    clientId: 'client-4',
    clientName: 'State PWD Department',
    type: 'Infrastructure',
    status: 'planning',
    location: 'Sabarmati, Ahmedabad',
    projectManager: 'Arun Mehta',
    startDate: '2026-10-01',
    endDate: '2027-06-30',
    budget: 32000000,
    spent: 0,
    progress: 0,
    description: 'Public riverfront plaza with amphitheater and walkways.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-15',
    code: 'PRJ-0015',
    name: 'Precision Auto Ancillary Unit 2',
    clientId: 'client-5',
    clientName: 'Precision Auto Components',
    type: 'Industrial',
    status: 'completed',
    location: 'Sriperumbudur, Chennai',
    projectManager: 'Priya Nair',
    startDate: '2025-06-01',
    endDate: '2026-02-28',
    budget: 19000000,
    spent: 18650000,
    progress: 100,
    description: 'Second ancillary manufacturing unit adjacent to the main plant.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
  {
    id: 'proj-16',
    code: 'PRJ-0016',
    name: 'Whitefield Tech Residency',
    clientId: 'client-1',
    clientName: 'Greenfield Developers',
    type: 'Residential',
    status: 'in_progress',
    location: 'Whitefield, Bengaluru',
    projectManager: 'Priya Nair',
    startDate: '2026-01-20',
    endDate: '2026-12-15',
    budget: 76000000,
    spent: 30500000,
    progress: 41,
    description: 'High-rise residential tower targeted at IT professionals.',
    milestones: [],
    tasks: [],
    expenses: [],
    documents: [],
  },
]
