import type { Lead } from './types'

export const LEADS_SEED: Lead[] = [
  {
    id: 'lead-1',
    name: 'Vikram Singh',
    phone: '+91 98765 43210',
    email: 'vikram.singh@example.com',
    projectType: '3BHK Villa Construction',
    estimatedBudget: 12500000,
    source: 'Website',
    status: 'new',
    assignedTo: 'Rohan Shah',
    location: 'Kondapur, Hyderabad',
    createdAt: '2026-07-04',
    followUps: [],
  },
  {
    id: 'lead-2',
    name: 'Meera Desai',
    phone: '+91 90000 11223',
    email: 'meera.desai@example.com',
    projectType: 'Duplex Renovation',
    estimatedBudget: 3200000,
    source: 'Referral',
    status: 'contacted',
    assignedTo: 'Rohan Shah',
    location: 'Baner, Pune',
    createdAt: '2026-06-30',
    followUps: [{ id: 'f1', note: 'Called, interested — scheduling site visit next week.', date: '2026-07-01' }],
  },
  {
    id: 'lead-3',
    name: 'Precision Auto Components',
    phone: '+91 98123 45678',
    email: 'procurement@precisionauto.in',
    projectType: 'Industrial Warehouse',
    estimatedBudget: 28000000,
    source: 'Advertisement',
    status: 'quoted',
    assignedTo: 'Arun Mehta',
    location: 'Oragadam, Chennai',
    createdAt: '2026-06-10',
    followUps: [
      { id: 'f1', note: 'Site visit completed, requirements finalized.', date: '2026-06-15' },
      { id: 'f2', note: 'Quotation of ₹2.8Cr sent for review.', date: '2026-06-22' },
    ],
  },
  {
    id: 'lead-4',
    name: 'Ananya Rao',
    phone: '+91 91234 56789',
    email: 'ananya.rao@example.com',
    projectType: 'Independent House',
    estimatedBudget: 8500000,
    source: 'Social Media',
    status: 'site_visit',
    assignedTo: 'Rohan Shah',
    location: 'Whitefield, Bengaluru',
    createdAt: '2026-06-25',
    followUps: [{ id: 'f1', note: 'Site visit scheduled for 2026-07-08.', date: '2026-06-27' }],
  },
  {
    id: 'lead-5',
    name: 'Greenfield Developers',
    phone: '+91 99887 76655',
    email: 'contact@greenfielddevs.com',
    projectType: 'Residential Complex - Phase 3',
    estimatedBudget: 95000000,
    source: 'Referral',
    status: 'won',
    assignedTo: 'Arun Mehta',
    location: 'Whitefield, Bengaluru',
    createdAt: '2026-05-12',
    followUps: [{ id: 'f1', note: 'Contract signed, converted to project.', date: '2026-06-01' }],
  },
  {
    id: 'lead-6',
    name: 'Karthik Iyer',
    phone: '+91 90909 80808',
    email: 'karthik.iyer@example.com',
    projectType: 'Farmhouse Construction',
    estimatedBudget: 4500000,
    source: 'Walk-in',
    status: 'lost',
    assignedTo: 'Rohan Shah',
    location: 'ECR, Chennai',
    createdAt: '2026-05-20',
    followUps: [{ id: 'f1', note: 'Went with a competitor offering lower quote.', date: '2026-06-05' }],
  },
  {
    id: 'lead-7',
    name: 'State PWD Department',
    phone: '+91 44 2345 6789',
    email: 'pwd.tenders@tn.gov.in',
    projectType: 'Bridge Widening Project',
    estimatedBudget: 45000000,
    source: 'Advertisement',
    status: 'contacted',
    assignedTo: 'Arun Mehta',
    location: 'NH-48, Chennai',
    createdAt: '2026-07-02',
    followUps: [],
  },
  { id: 'lead-8', name: 'Nandini Constructions Pvt Ltd', phone: '+91 98111 23456', email: 'info@nandiniconstructions.in', projectType: 'Joint Development — Apartments', estimatedBudget: 62000000, source: 'Referral', status: 'new', assignedTo: 'Rohan Shah', location: 'Jayanagar, Bengaluru', createdAt: '2026-07-03', followUps: [] },
  { id: 'lead-9', name: 'Orion Realty Group', phone: '+91 98222 44556', email: 'contact@orionrealty.in', projectType: 'Commercial Complex', estimatedBudget: 41000000, source: 'Website', status: 'contacted', assignedTo: 'Arun Mehta', location: 'Adyar, Chennai', createdAt: '2026-06-28', followUps: [] },
  { id: 'lead-10', name: 'BlueWave Textiles Ltd', phone: '+91 98333 55667', email: 'facilities@bluewavetextiles.com', projectType: 'Factory Expansion', estimatedBudget: 18000000, source: 'Advertisement', status: 'quoted', assignedTo: 'Arun Mehta', location: 'Tirupur, Tamil Nadu', createdAt: '2026-06-15', followUps: [] },
  { id: 'lead-11', name: 'Suresh Patel', phone: '+91 98444 66778', email: 'suresh.patel@example.com', projectType: 'Duplex House', estimatedBudget: 5200000, source: 'Walk-in', status: 'site_visit', assignedTo: 'Rohan Shah', location: 'Satellite, Ahmedabad', createdAt: '2026-06-20', followUps: [] },
  { id: 'lead-12', name: 'Horizon Hospitality Pvt Ltd', phone: '+91 98555 77889', email: 'projects@horizonhospitality.in', projectType: 'Boutique Hotel', estimatedBudget: 74000000, source: 'Referral', status: 'won', assignedTo: 'Arun Mehta', location: 'Koramangala, Bengaluru', createdAt: '2026-05-01', followUps: [] },
  { id: 'lead-13', name: 'National Highways Authority', phone: '+91 11 2345 6789', email: 'regional.south@nhai.gov.in', projectType: 'Highway Underpass', estimatedBudget: 89000000, source: 'Advertisement', status: 'new', assignedTo: 'Arun Mehta', location: 'Trichy Bypass', createdAt: '2026-07-01', followUps: [] },
  { id: 'lead-14', name: 'Ravi Shankar', phone: '+91 90111 22334', email: 'ravi.shankar@example.com', projectType: 'Weekend Farmhouse', estimatedBudget: 3800000, source: 'Social Media', status: 'contacted', assignedTo: 'Rohan Shah', location: 'Nandi Hills Road, Bengaluru', createdAt: '2026-06-29', followUps: [] },
  { id: 'lead-15', name: 'Deepika Menon', phone: '+91 90222 33445', email: 'deepika.menon@example.com', projectType: 'Renovation — Kitchen & Facade', estimatedBudget: 1200000, source: 'Walk-in', status: 'quoted', assignedTo: 'Rohan Shah', location: 'Anna Nagar, Chennai', createdAt: '2026-06-18', followUps: [] },
  { id: 'lead-16', name: 'TechSpace Coworking LLP', phone: '+91 90333 44556', email: 'expansion@techspace.co', projectType: 'Coworking Fit-out', estimatedBudget: 9500000, source: 'Website', status: 'site_visit', assignedTo: 'Arun Mehta', location: 'Hitech City, Hyderabad', createdAt: '2026-06-24', followUps: [] },
  { id: 'lead-17', name: 'Farhan Ali', phone: '+91 90444 55667', email: 'farhan.ali@example.com', projectType: 'Row House Construction', estimatedBudget: 6700000, source: 'Referral', status: 'lost', assignedTo: 'Rohan Shah', location: 'Kalyan Nagar, Bengaluru', createdAt: '2026-05-28', followUps: [] },
  { id: 'lead-18', name: 'Greater Municipal Corporation', phone: '+91 44 2233 4455', email: 'works@gmc.gov.in', projectType: 'Public Park Redevelopment', estimatedBudget: 15500000, source: 'Advertisement', status: 'contacted', assignedTo: 'Arun Mehta', location: 'T. Nagar, Chennai', createdAt: '2026-06-30', followUps: [] },
  { id: 'lead-19', name: 'Priyanka Bose', phone: '+91 90555 66778', email: 'priyanka.bose@example.com', projectType: 'Studio Apartment Block', estimatedBudget: 22000000, source: 'Social Media', status: 'new', assignedTo: 'Rohan Shah', location: 'Salt Lake, Kolkata', createdAt: '2026-07-04', followUps: [] },
  { id: 'lead-20', name: 'Global Foods Pvt Ltd', phone: '+91 90666 77889', email: 'infra@globalfoods.in', projectType: 'Cold Storage Warehouse', estimatedBudget: 34000000, source: 'Website', status: 'quoted', assignedTo: 'Arun Mehta', location: 'Sriperumbudur, Chennai', createdAt: '2026-06-12', followUps: [] },
]
