import type { NotificationItem } from './types'

export const NOTIFICATIONS_SEED: NotificationItem[] = [
  {
    id: 'ntf-1',
    title: 'New lead assigned',
    description: 'Vikram Singh submitted an inquiry for a 3BHK villa construction.',
    createdAt: '2026-07-04T08:30:00.000Z',
    read: false,
    type: 'info',
  },
  {
    id: 'ntf-2',
    title: 'Payment received',
    description: '₹4,50,000 received from Greenfield Developers for Riverside Towers.',
    createdAt: '2026-07-03T15:10:00.000Z',
    read: false,
    type: 'success',
  },
  {
    id: 'ntf-3',
    title: 'Low stock alert',
    description: 'Cement (OPC 53 Grade) stock is below reorder threshold at Site B.',
    createdAt: '2026-07-03T09:00:00.000Z',
    read: false,
    type: 'warning',
  },
  {
    id: 'ntf-4',
    title: 'Task overdue',
    description: 'Electrical conduit layout for Block C was due yesterday.',
    createdAt: '2026-07-02T18:45:00.000Z',
    read: true,
    type: 'destructive',
  },
  {
    id: 'ntf-5',
    title: 'Contract approved',
    description: 'Purchase order PO-2091 for steel rebar has been approved.',
    createdAt: '2026-07-01T11:20:00.000Z',
    read: true,
    type: 'success',
  },
  { id: 'ntf-6', title: 'New follow-up logged', description: 'A follow-up note was added to the BlueWave Textiles lead.', createdAt: '2026-06-30T14:05:00.000Z', read: true, type: 'info' },
  { id: 'ntf-7', title: 'Invoice overdue', description: 'INV-2026-011 for Precision Auto Warehouse is now overdue.', createdAt: '2026-06-29T09:40:00.000Z', read: true, type: 'destructive' },
  { id: 'ntf-8', title: 'Equipment due for service', description: 'Tipper Truck TT-07 is due for maintenance this week.', createdAt: '2026-06-28T16:15:00.000Z', read: true, type: 'warning' },
  { id: 'ntf-9', title: 'New document uploaded', description: 'Environmental Clearance Application uploaded for Tech Park Block D.', createdAt: '2026-06-27T10:00:00.000Z', read: true, type: 'info' },
  { id: 'ntf-10', title: 'Site progress logged', description: 'Daily site report submitted for Coastal Logistics Park.', createdAt: '2026-06-26T18:30:00.000Z', read: true, type: 'success' },
  { id: 'ntf-11', title: 'Lead converted', description: 'Greenfield Developers lead converted to Riverside Towers Phase 3.', createdAt: '2026-06-25T12:00:00.000Z', read: true, type: 'success' },
  { id: 'ntf-12', title: 'New estimate sent', description: 'BOQ sent to Orion Realty Group for Commercial Complex.', createdAt: '2026-06-24T09:15:00.000Z', read: true, type: 'info' },
  { id: 'ntf-13', title: 'Purchase order pending approval', description: 'PO-2144 for boundary wall materials needs review.', createdAt: '2026-06-23T15:45:00.000Z', read: true, type: 'warning' },
  { id: 'ntf-14', title: 'Task completed', description: 'Structural audit for Tower A marked complete.', createdAt: '2026-06-22T13:10:00.000Z', read: true, type: 'success' },
  { id: 'ntf-15', title: 'Vendor rating updated', description: 'Classic Tiles & Sanitaryware marked inactive.', createdAt: '2026-06-21T11:30:00.000Z', read: true, type: 'info' },
]
