import type { Client } from './types'

export const CLIENTS_SEED: Client[] = [
  {
    id: 'client-1',
    name: 'Greenfield Developers',
    contactPerson: 'Ramesh Gowda',
    phone: '+91 99887 76655',
    email: 'contact@greenfielddevs.com',
    address: 'MG Road, Bengaluru',
    type: 'Developer',
    createdAt: '2025-08-10',
    contactHistory: [
      { id: 'c1', note: 'Signed contract for Riverside Towers.', date: '2026-01-05' },
      { id: 'c2', note: 'Discussed Phase 3 requirements.', date: '2026-05-12' },
    ],
  },
  {
    id: 'client-2',
    name: 'Vikram Singh',
    contactPerson: 'Vikram Singh',
    phone: '+91 98765 43210',
    email: 'vikram.singh@example.com',
    address: 'Kondapur, Hyderabad',
    type: 'Individual',
    createdAt: '2026-02-20',
    contactHistory: [{ id: 'c1', note: 'Finalized villa design and signed agreement.', date: '2026-03-01' }],
  },
  {
    id: 'client-3',
    name: 'Skyline Infra Ltd',
    contactPerson: 'Neha Kapoor',
    phone: '+91 98123 45678',
    email: 'neha.kapoor@skylineinfra.com',
    address: 'Hinjewadi, Pune',
    type: 'Corporate',
    createdAt: '2026-05-01',
    contactHistory: [{ id: 'c1', note: 'Kickoff meeting for Tech Park Block D.', date: '2026-06-01' }],
  },
  {
    id: 'client-4',
    name: 'State PWD Department',
    contactPerson: 'K. Subramaniam',
    phone: '+91 44 2345 6789',
    email: 'pwd.tenders@tn.gov.in',
    address: 'Chennai',
    type: 'Government',
    createdAt: '2025-03-15',
    contactHistory: [{ id: 'c1', note: 'Bridge retrofit project handed over.', date: '2026-04-02' }],
  },
  {
    id: 'client-5',
    name: 'Precision Auto Components',
    contactPerson: 'Suresh Babu',
    phone: '+91 98123 00011',
    email: 'procurement@precisionauto.in',
    address: 'Oragadam, Chennai',
    type: 'Corporate',
    createdAt: '2026-01-25',
    contactHistory: [],
  },
  { id: 'client-6', name: 'Nandini Constructions Pvt Ltd', contactPerson: 'Nandini Rao', phone: '+91 98111 23456', email: 'info@nandiniconstructions.in', address: 'Jayanagar, Bengaluru', type: 'Developer', createdAt: '2026-02-01', contactHistory: [] },
  { id: 'client-7', name: 'Ananya Rao', contactPerson: 'Ananya Rao', phone: '+91 91234 56789', email: 'ananya.rao@example.com', address: 'Whitefield, Bengaluru', type: 'Individual', createdAt: '2026-06-25', contactHistory: [] },
  { id: 'client-8', name: 'Meera Desai', contactPerson: 'Meera Desai', phone: '+91 90000 11223', email: 'meera.desai@example.com', address: 'Baner, Pune', type: 'Individual', createdAt: '2026-06-30', contactHistory: [] },
  { id: 'client-9', name: 'Karthik Iyer', contactPerson: 'Karthik Iyer', phone: '+91 90909 80808', email: 'karthik.iyer@example.com', address: 'ECR, Chennai', type: 'Individual', createdAt: '2026-05-20', contactHistory: [] },
  { id: 'client-10', name: 'Orion Realty Group', contactPerson: 'Vivek Chandran', phone: '+91 98222 44556', email: 'contact@orionrealty.in', address: 'Adyar, Chennai', type: 'Developer', createdAt: '2025-11-12', contactHistory: [] },
  { id: 'client-11', name: 'Greater Municipal Corporation', contactPerson: 'S. Elango', phone: '+91 44 2233 4455', email: 'works@gmc.gov.in', address: 'Ripon Building, Chennai', type: 'Government', createdAt: '2025-05-18', contactHistory: [] },
  { id: 'client-12', name: 'BlueWave Textiles Ltd', contactPerson: 'Ritu Sharma', phone: '+91 98333 55667', email: 'facilities@bluewavetextiles.com', address: 'Tirupur, Tamil Nadu', type: 'Corporate', createdAt: '2026-03-22', contactHistory: [] },
  { id: 'client-13', name: 'Suresh & Family', contactPerson: 'Suresh Patel', phone: '+91 98444 66778', email: 'suresh.patel@example.com', address: 'Satellite, Ahmedabad', type: 'Individual', createdAt: '2026-04-05', contactHistory: [] },
  { id: 'client-14', name: 'Horizon Hospitality Pvt Ltd', contactPerson: 'Anjali Menon', phone: '+91 98555 77889', email: 'projects@horizonhospitality.in', address: 'Koramangala, Bengaluru', type: 'Corporate', createdAt: '2026-01-08', contactHistory: [] },
  { id: 'client-15', name: 'National Highways Authority', contactPerson: 'R. Venkataraman', phone: '+91 11 2345 6789', email: 'regional.south@nhai.gov.in', address: 'New Delhi', type: 'Government', createdAt: '2025-02-14', contactHistory: [] },
]
